name: 'Setup Database'
description: 'Sets up PostgreSQL database with test data for integration tests'
inputs:
  working-directory:
    description: 'Working directory containing .env.test file'
    required: true
    default: './backend'

runs:
  using: 'composite'
  steps:
    - name: Install PostgreSQL client
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Set up database
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |      
        # Copy test environment file
        cp .env.test .env
        
        # Read database configuration from .env.test
        export $(grep -v '^#' .env.test | xargs)

        echo "Database config: POSTGRES_DB=$POSTGRES_DB, POSTGRES_USER=$POSTGRES_USER"
        
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        
        # Verify database connection
        echo "Verifying database connection..."
        PGPASSWORD="$POSTGRES_PASSWORD" psql -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT version();" || {
          echo "Failed to connect to database $POSTGRES_DB as user $POSTGRES_USER"
          exit 1
        }
        
        # Create recipes table 
        echo "Creating recipes table..."
        PGPASSWORD="$POSTGRES_PASSWORD" psql -h localhost -U "$POSTGRES_USER" -d "$PGDATABASE" -c "
        CREATE TABLE IF NOT EXISTS recipes (
          id SERIAL PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          category VARCHAR(20) CHECK (category IN ('breakfast', 'lunch', 'dinner', 'snack')),
          main_ingredients JSONB,
          common_ingredients TEXT[] DEFAULT '{}',
          instructions TEXT NOT NULL,
          prep_time INTEGER,
          portions INTEGER,
          foto_url VARCHAR(255),
          video_url VARCHAR(255)
        );"

        # Create meal_plans table
        echo "Creating meal_plans table..."
        PGPASSWORD="$POSTGRES_PASSWORD" psql -h localhost -U "$POSTGRES_USER" -d "$PGDATABASE" -c "
        CREATE TABLE IF NOT EXISTS meal_plans (
          id SERIAL PRIMARY KEY,
          week_start DATE NOT NULL,
          day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
          meal_slot VARCHAR(20) NOT NULL CHECK (meal_slot IN ('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner')),
          recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
          UNIQUE(week_start, day_of_week, meal_slot)
        );"

        # Insert sample recipe
        echo "Inserting sample recipe data..."
        PGPASSWORD="$POSTGRES_PASSWORD" psql -h localhost -U "$POSTGRES_USER" -d "$PGDATABASE" -c "
        INSERT INTO recipes (name, category, main_ingredients, common_ingredients, instructions, prep_time, portions, foto_url, video_url) 
        VALUES (
          'Test Pasta', 
          'dinner', 
          '[
            {\"name\": \"pasta\", \"unit\": \"g\", \"quantity\": 250},
            {\"name\": \"tomato\", \"unit\": \"g\", \"quantity\": 500},
            {\"name\": \"onion\", \"unit\": \"pcs\", \"quantity\": 1},
            {\"name\": \"burrata\", \"unit\": \"pcs\", \"quantity\": 1}
          ]'::jsonb,
          ARRAY['salt', 'pepper', 'basil', 'olive', 'garlic'],
          'Cook pasta and add oil',
          15,
          2,
          'www.my-foto-url.net',
          'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
        ) ON CONFLICT DO NOTHING;"
        
        echo "Database setup completed successfully!"
